###########################
# General Configuration ###
###########################
processes = 16

[cobra]
solver = "hybrid"

##############################
# Simulation Configuration ###
##############################

[simulation.to-ignore]
subsystems = ["Biomass", "External Exchange Reactions"]
compartments = ["E"]

[simulation.reaction-bounds]
external-exchange = [-100, 100]
internal-reversible = [-50, 50]
internal-forward = [0, 50]
import-reversible = [-50, 50]
export-irreversible = [0, 50]

[simulation.metabolite-networks]
essential-proportion = 0.10
reaction-proportion = 0.10

[simulation.metabolic-network]
directed = false

[simulation.divergence]
n-neighbors = 5
num-samples = 1000
use-unperturbed-as-true = true
jitter = 1e-13
type = "kl"

[simulation.mutual-information]
n-neighbors = 3
x-metric = 2.0
y-metric = 2.0

[simulation.flux-sampling]
num-samples = 1000
thinning = 500

[simulation.target-density]
radius-list = [0, 1, 2, 3]
targeted-genes = ["g006", "g011", "g024"]

[simulation.imat]
epsilon = 10.0
threshold = 0.00001
objective-tolerance = 0.01
up-regulated-genes = ["g014", "g020", "g017", "g008"]
down-regulated-genes = ["g013", "g023"]

##########################
# Mtb TF Configuration ###
##########################
[mtb_tf.imat]
epsilon = 1.0
threshold = 0.01
neg-fold-change = -1
pos-fold-change = 1
objective-tolerance = 5e-2

[mtb_tf.sampling]
thinning = 500
num-samples = 1000

[mtb_tf.divergence]
n-neighbors = 5
metric = 2.0
essential-proportion = 0.1
reaction-proportion = 0.1
correlation-cutoff = 0.75
progress-bar = false

[mtb_tf.ko_divergence]
sample-count = 1_000      # Number of samples to use when calclating divergence
n-neighbors = 5           # Number of neighbors to use in divergence estimation
target-fc-cutoff = 1.0    # Log2(fold-change) cutoff for considering a gene a TF target
target-pval-cutoff = 0.05 # P-value cutoff for considering a gene a TF target
min-target-count = 5      # Minimum number of targets in model for calculating enrichment
fba_ess_threshold = 0.1   # Proportion of optimal growth, below which a gene is considered essential 

[mtb_tf.target_density]
exclude-top-n-met = 10
radius = 1
target-fc-cutoff = 1.0
target-pval-cutoff = 0.05

[mtb_tf.network_properties]
directed = true
bootstrap-iterations = 1_000
exclude-top-n-met = 10
bootrap-method = "kernel"
bootstrap-alternative = "greater"
target-fc-cutoff = 1.0
target-pval-cutoff = 0.05

[mtb_tf.metabolite_gsva]
essential-proportion = 0.1
reaction-proportion = 0.1

[mtb_tf.target_enrichment]
essential-proportion = 0.1 # Number of samples to use when calclating divergence
reaction-proportion = 0.1  # Number of neighbors to use in divergence estimation
target-fc-cutoff = 1.0     # Log2(fold-change) cutoff for considering a gene a TF target
target-pval-cutoff = 0.05  # P-value cutoff for considering a gene a TF target

[mtb_tf.mutual_information]
target-fc-cutoff = 1.0    # Log2(fold-change) cutoff for considering a gene a TF target
target-pval-cutoff = 0.05 # P-value cutoff for considering a gene a TF target
min-target-count = 5      # Minimum number of targets in model for calculating p-value
