[workspace]
authors = ["Braden Griebel <bgriebel@uw.edu>"]
channels = ["conda-forge"]
name = "simulation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
create_model = { cmd = "python 01_create_model.py", cwd = "scripts/simulation" }
find_metabolite_networks = { cmd = "python 02_metabolite_networks.py", cwd = "scripts/simulation" }
metabolic_network_analysis = { cmd = "python 03_metabolic_network_analysis.py", cwd = "scripts/simulation" }
ko_divergence = { cmd = "python 04_ko_divergence.py", cwd = "scripts/simulation" }
mi_network = { cmd = "python 05_mutual_information.py", cwd = "scripts/simulation" }
density = { cmd = "python 06_density.py", cwd = "scripts/simulation" }
imat = { cmd = "python 07_imat_simulation.py", cwd = "scripts/simulation" }
visualization_script = { cmd = "python 08_visualization.py", cwd = "scripts/simulation" }
viz = [{ task = "visualization_script", environment = "viz" }]
simulation = [
  { task = "create_model", environment = "default" },
  { task = "find_metabolite_networks", environment = "default" },
  { task = "metabolic_network_analysis", environment = "default" },
  { task = "ko_divergence", environment = "default" },
  { task = "mi_network", environment = "default" },
  { task = "density", environment = "default" },
  { task = "imat", environment = "default" },
  { task = "visualization_script", environment = "viz" },
]
tf_reaction_info = { cmd = "python 00_reaction_info.py", cwd = "scripts/mtb_transcription_factor" }
tf_metabolite_info = { cmd = "python 00_metabolite_info.py", cwd = "scripts/mtb_transcription_factor" }
tf_gen_model = { cmd = "python 01_model_generation.py", cwd = "scripts/mtb_transcription_factor" }
tf_sample_model = { cmd = "python 02_model_sampling.py", cwd = "scripts/mtb_transcription_factor" }
tf_divergence = { cmd = "python 03_divergence.py", cwd = "scripts/mtb_transcription_factor" }
tf_ko_divergence = { cmd = "python 04_tf_ko_divergence.py", cwd = "scripts/mtb_transcription_factor" }
tf_target_density = { cmd = "python 05_tf_target_density.py", cwd = "scripts/mtb_transcription_factor" }
tf_reaction_centrality = { cmd = "python 06_reaction_network_centrality.py", cwd = "scripts/mtb_transcription_factor" }
tf_metabolite_gsva_private = { cmd = "python 07_metabolite_gsva.py", cwd = "scripts/mtb_transcription_factor" }
tf_metabolite_gsva = [
  { task = "tf_metabolite_gsva_private", environment = "decoupler" },
]
tf_metabolite_enrichment = { cmd = "python 08_metabolite_network_target_enrichment.py", cwd = "scripts/mtb_transcription_factor" }
mtb_tf = [
  { task = "tf_reaction_info", environment = "default" },
  { task = "tf_metabolite_info", environment = "default" },
  { task = "tf_gen_model", environment = "default" },
  { task = "tf_sample_model", environment = "default" },
  { task = "tf_divergence", environment = "default" },
  { task = "tf_ko_divergence", environment = "default" },
  { task = "tf_target_density", environment = "default" },
  { task = "tf_reaction_centrality", environment = "default" },
  { task = "tf_metabolite_gsva_private", environment = "decoupler" },
  { task = "tf_metabolite_enrichment", environment = "default" },
]

[dependencies]
python = ">=3.13.10,<3.14"
cobra = ">=0.30.0,<0.31"
scipy = ">=1.16.3,<2"
networkx = ">=3.6,<4"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
optlang = ">=1.8.3,<2"
sympy = ">=1.14.0,<2"
tqdm = ">=4.67.1,<5"
pyarrow = ">=22.0.0,<23"
joblib = ">=1.5.2,<2"
osqp = ">=1.0.5,<2"
highspy = ">=1.12.0,<2"
openpyxl = ">=3.1.5,<4"
r-base = ">=4.5.2,<4.6"
r-robustrankaggreg = ">=1.2.1,<2"
rpy2 = ">=3.6.4,<4"

[pypi-dependencies]
metworkpy = { git = "https://github.com/Ma-Lab-Seattle-Childrens-CGIDR/metworkpy.git" }
metabolic-modeling-utils = { git = "https://github.com/Braden-Griebel/metabolic_modeling_utils.git" }

[feature.dev.dependencies]
mypy = ">=1.19.0,<2"
ruff = ">=0.14.8,<0.15"
python-lsp-server = ">=1.13.2,<2"
pandas-stubs = ">=2.3.3.251201,<3"
taplo = ">=0.10.0,<0.11"
types-networkx = ">=3.6.0.20251127,<4"

[feature.escher.pypi-dependencies]
Escher = ">=1.8.1, <2"

[feature.viz.dependencies]
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
networkx = ">=3.6.1,<4"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"

[feature.viz.pypi-dependencies]
iplotx = ">=1.6.0, <2"

[feature.decoupler.dependencies]
decoupler-py = "*"

[environments]
dev = ["dev", "default"]
decoupler = ["default", "decoupler"]
viz = ["escher", "viz", "default"]
vdev = ["escher", "viz", "dev"]
